#!/usr/bin/env python3
#
# Filename: vulnscanner.py
#
# Violent Python - A Cookbook for Hackers,Forensic Analysts,Penetration Testers and Security Engineers
# Chapter < N > | < EXAMPLE DESCRIPTION > - version < N >
#
# NOTE: This is a modified version of the final version of the < DESCRIPTION > from pages < N > through < N >.
#
# Original Author: TJ O'Connor
# Modified to run under Python 3.x by: Daniel Raphael
#

